### ISSUE TITLE
Don't invert that matrix

### ISSUE THREAD

**Issue by ivan-pi** [jvendrow/fnnls#5]
https://github.com/jvendrow/fnnls/blob/9fa53452e5ee92b50de85bcae7d64c530af85d3a/src/fnnls/fnnls.py#L3

Wouldn't it be preferable to use [`numpy.linalg.lstsq`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html#numpy.linalg.lstsq) instead of forming an explicit inverse?

See also:
* [Don't invert that matrix](https://www.johndcook.com/blog/2010/01/19/dont-invert-that-matrix/)
* [Why Shouldn't I Invert That Matrix?](https://gregorygundersen.com/blog/2020/12/09/matrix-inversion/)

**Comment by jvendrow** [comment]
Hi Ivan! When I was writing this code and choosing the way to do the least squares operation I tried out multiple options, including using [`numpy.linalg.lstsq`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html#numpy.linalg.lstsq), but after timing analysis I found it faster to do the explicit inverse in this situation. Theoretically, I agree in many cases it might be better to use the [`numpy.linalg.lstsq`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html#numpy.linalg.lstsq) function as you suggest.

As a side note, I included the least squares function as a parameter specifically for this reason, so that users can choose which form of this operation to use. Calling `fnnls(Z, x, lstsq = np.linalg.lstsq)` allows users to use the direct lstsq function instead if they wish!
